repos:
  - repo: https://github.com/hhatto/autopep8
    rev: master
    hooks:
      - id: autopep8
        args: ["--max-line-length=100", "--ignore=E501,W6", "--aggressive", "--aggressive", "--aggressive"]

